### ISSUE TITLE
视频播放还有些问题，打开视频页面不会自动播放视频，已更新1.3.6版本。

### ISSUE THREAD

**Issue by visneas** [CN1984/LearningThePooh#27] opened 2019-04-18 02:14 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CN1984** [comment] 2019-04-18 09:44
Duplicate of #20

**Closed by CN1984** 2019-04-18 09:44 UTC
